// Code generated by modes/gen. DO NOT EDIT.

// Package all holds the generated mode registry list: one import and one
// New() call per mode package under internal/modes (STYLE.md §1, §10). It is
// a child of modes rather than modes itself because every mode package
// imports modes for the Mode interface, and a package cannot import its own
// importers.
package all

import (
	"forge/internal/core/modes"
	"forge/internal/core/modes/audit"
	"forge/internal/core/modes/curate"
	"forge/internal/core/modes/docs"
	"forge/internal/core/modes/explore"
	"forge/internal/core/modes/greenfield"
	"forge/internal/core/modes/implement"
	"forge/internal/core/modes/intake"
	"forge/internal/core/modes/integrate"
	"forge/internal/core/modes/maintain"
	"forge/internal/core/modes/plan"
	"forge/internal/core/modes/retro"
	"forge/internal/core/modes/review"
	"forge/internal/core/modes/run"
	"forge/internal/core/modes/supervise"
	"forge/internal/core/modes/verify"
)

// All returns one value of every mode, sorted by name; cmd/forge feeds it
// to modes.NewRegistry and modes.Seeds.
func All() []modes.Mode {
	return []modes.Mode{
		audit.New(),
		curate.New(),
		docs.New(),
		explore.New(),
		greenfield.New(),
		implement.New(),
		intake.New(),
		integrate.New(),
		maintain.New(),
		plan.New(),
		retro.New(),
		review.New(),
		run.New(),
		supervise.New(),
		verify.New(),
	}
}
