#!/usr/bin/env bash
# Build and pack a Forge release archive: forge-<version>-<target>.tar.gz
# beside a SHA256SUMS file, both left in dist/. Run by hand, or by
# .github/workflows/release.yml on a v* tag once .github exists (see
# docs/OPS.md, "Releases"). The version is not a guess: it is read back
# from the built `forge version` itself, so the archive is always named
# what the binary inside it reports and what the release should be tagged.
#
# Usage: scripts/release.sh [target-triple]
# Default target is the host triple `rustc` reports; a different one
# assumes its toolchain is already installed and passes it to `cargo
# build` as `--target`.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

host="$(rustc -vV | sed -n 's/^host: //p')"
target="${1:-$host}"

# The workspace's own binaries. Unit-tested against every member's
# Cargo.toml in tests/release.rs, so a new crate that builds a binary and
# is not added here fails `cargo test --workspace` instead of shipping
# silently short. forge-test is not a crate yet; add it here the day it is.
BINS="forge forge-web forge-portal forge-tui forge-repomap forge-test"

echo "building $target release..." >&2
if [ "$target" = "$host" ]; then
  cargo build --release --workspace
  rel="$root/target/release"
else
  cargo build --release --workspace --target "$target"
  rel="$root/target/$target/release"
fi

for b in $BINS; do
  if [ ! -x "$rel/$b" ]; then
    echo "release.sh: the build produced no $rel/$b" >&2
    exit 1
  fi
done

version="$("$rel/forge" version | cut -d' ' -f1)"
name="forge-$version-$target"
out="$root/dist"
pkgdir="$out/$name"
rm -rf "$pkgdir"
mkdir -p "$pkgdir"

for b in $BINS; do
  cp -p "$rel/$b" "$pkgdir/$b"
done
cp -p "$root/deploy/forge-worker.service" "$pkgdir/forge-worker.service"
cp -p "$root/docs/ops/forge-web.service" "$pkgdir/forge-web.service"

# The operator's config.toml template: generated by the binary just built,
# not hand-copied, so the packed template can never drift from
# `config::DEFAULT_HOME_CONFIG`, the one place it is written. A read-only
# command that goes through `Forge::open` is enough to trigger it, no
# network or agent needed.
scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT
FORGE_HOME="$scratch" "$rel/forge" project list >/dev/null
cp -p "$scratch/config.toml" "$pkgdir/config.toml"

tar -C "$out" -czf "$out/$name.tar.gz" "$name"
rm -rf "$pkgdir"

sums="$out/SHA256SUMS"
sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1"
  else
    shasum -a 256 "$1"
  fi
}
touch "$sums"
grep -v " $name.tar.gz\$" "$sums" > "$sums.tmp" || true
mv "$sums.tmp" "$sums"
(cd "$out" && sha256 "$name.tar.gz") >> "$sums"

echo "packed $out/$name.tar.gz" >&2
