//! Forge: one binary, no daemon. `forge run <repo> "<task>"` creates a
//! worktree, runs the agent in it under bubblewrap with a wall-clock
//! timeout, verifies the result at three levels, retries with the failure
//! as feedback, pushes on success, and records every attempt. `forge add`
//! queues the same thing and `forge work` drains the queue.

mod agent;
#[cfg(test)]
mod argument_policy_tests;
mod assess;
mod attempt;
mod audit;
mod binary;
mod checks;
mod cli;
mod concierge;
mod config;
mod ctx;
mod deploy;
mod deploy_look;
mod directive;
mod doctor;
mod egress;
mod engine;
mod env_supervisor;
mod envelope;
mod environment;
mod executor;
mod experiment;

mod git;
mod graph;
mod handoff;
mod init;
mod intake;
mod job;
mod journal;
mod landing;
mod operation;
mod plugins;
mod pricing;
mod profile;
mod prompts;
mod queue;
mod release;
mod render;
mod report;
mod sandbox;
mod store;
mod supervisor;
mod tools;
mod upgrade;
mod verify;
mod view;
mod worker;
mod workflows;

use std::time::{SystemTime, UNIX_EPOCH};

pub fn unix_now() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    cli::main().await
}

#[cfg(test)]
mod readme_layout {
    use std::fs;
    use std::path::Path;

    // README.md's "Layout" section is generated by hand, not by the
    // compiler, so nothing stops it drifting from the tree the way rustc
    // stops a stale `mod` list. This test is that stop: every source file
    // and workspace crate has to be named there, or it fails.
    #[test]
    fn every_module_and_crate_is_named_in_the_readme() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let readme = fs::read_to_string(root.join("README.md")).expect("read README.md");

        let mut missing = Vec::new();

        for dir in ["src", "src/store"] {
            for entry in fs::read_dir(root.join(dir)).expect("read_dir") {
                let path = entry.expect("dir entry").path();
                if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                    continue;
                }
                let name = path.file_name().unwrap().to_str().unwrap().to_string();
                if !readme.contains(&name) {
                    missing.push(format!("{dir}/{name}"));
                }
            }
        }

        let cargo_toml = fs::read_to_string(root.join("Cargo.toml")).expect("read Cargo.toml");
        let members_line = cargo_toml
            .lines()
            .find(|l| l.trim_start().starts_with("members"))
            .expect("workspace members line in Cargo.toml");
        for member in members_line
            .split(['[', ']', '"', ',', '='])
            .map(|s| s.trim())
            .filter(|s| !s.is_empty() && *s != "members")
        {
            if !readme.contains(&format!("{member}/")) {
                missing.push(format!("workspace member {member}"));
            }
        }

        assert!(
            missing.is_empty(),
            "README.md's Layout section doesn't name: {missing:?}"
        );
    }
}

#[cfg(test)]
mod docs_readme_index {
    use std::collections::BTreeSet;
    use std::fs;
    use std::path::Path;

    // docs/README.md is the hand-written index of everything under docs/.
    // This is the stop that keeps it from going stale: every docs/*.md file
    // has to be named there, and every *.md name it mentions has to exist.
    fn walk_md(dir: &Path, prefix: &str, out: &mut Vec<String>) {
        for entry in fs::read_dir(dir).expect("read_dir") {
            let path = entry.expect("dir entry").path();
            let name = path.file_name().unwrap().to_str().unwrap().to_string();
            if path.is_dir() {
                walk_md(&path, &format!("{prefix}{name}/"), out);
            } else if path.extension().and_then(|e| e.to_str()) == Some("md") {
                out.push(format!("{prefix}{name}"));
            }
        }
    }

    #[test]
    fn every_doc_is_indexed_and_the_index_names_only_real_files() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let docs = root.join("docs");
        let index = fs::read_to_string(docs.join("README.md")).expect("read docs/README.md");

        let tokens: BTreeSet<&str> = index
            .split(|c: char| c.is_whitespace() || "[]()`,*:".contains(c))
            .filter(|word| !word.is_empty())
            .collect();

        let mut all = Vec::new();
        walk_md(&docs, "", &mut all);

        let mut missing = Vec::new();
        for rel in &all {
            if rel == "README.md" {
                continue;
            }
            let covered = match rel.split_once('/') {
                Some((dir, _)) => {
                    tokens.contains(rel.as_str()) || tokens.contains(format!("{dir}/").as_str())
                }
                None => tokens.contains(rel.as_str()),
            };
            if !covered {
                missing.push(rel.clone());
            }
        }
        assert!(
            missing.is_empty(),
            "docs/README.md doesn't index: {missing:?}"
        );

        let mut dangling = Vec::new();
        for word in &tokens {
            let word = word.trim_matches('/');
            if !word.ends_with(".md") {
                continue;
            }
            if !docs.join(word).is_file() {
                dangling.push(word.to_string());
            }
        }
        assert!(
            dangling.is_empty(),
            "docs/README.md names files that don't exist: {dangling:?}"
        );
    }
}
