//! Forge 2: one binary, no daemon. `forge run <repo> "<task>"` creates a
//! worktree, runs the agent in it under bubblewrap with a wall-clock
//! timeout, verifies the result at three levels, retries with the failure
//! as feedback, pushes on success, and records every attempt. `forge add`
//! queues the same thing and `forge work` drains the queue.

mod agent;
mod assess;
mod attempt;
mod audit;
mod checks;
mod cli;
mod concierge;
mod config;
mod ctx;
mod deploy;
mod deploy_look;
mod directive;
mod doctor;
mod egress;
mod engine;
mod envelope;

mod git;
mod intake;
mod job;
mod journal;
mod landing;
mod operation;
mod plugins;
mod profile;
mod prompts;
mod queue;
mod render;
mod report;
mod sandbox;
mod store;
mod supervisor;
mod tools;
mod verify;
mod view;
mod worker;
mod workflows;

use std::time::{SystemTime, UNIX_EPOCH};

pub fn unix_now() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    cli::main().await
}

#[cfg(test)]
mod readme_layout {
    use std::fs;
    use std::path::Path;

    // README.md's "Layout" section is generated by hand, not by the
    // compiler, so nothing stops it drifting from the tree the way rustc
    // stops a stale `mod` list. This test is that stop: every source file
    // and workspace crate has to be named there, or it fails.
    #[test]
    fn every_module_and_crate_is_named_in_the_readme() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let readme = fs::read_to_string(root.join("README.md")).expect("read README.md");

        let mut missing = Vec::new();

        for dir in ["src", "src/store"] {
            for entry in fs::read_dir(root.join(dir)).expect("read_dir") {
                let path = entry.expect("dir entry").path();
                if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                    continue;
                }
                let name = path.file_name().unwrap().to_str().unwrap().to_string();
                if !readme.contains(&name) {
                    missing.push(format!("{dir}/{name}"));
                }
            }
        }

        let cargo_toml = fs::read_to_string(root.join("Cargo.toml")).expect("read Cargo.toml");
        let members_line = cargo_toml
            .lines()
            .find(|l| l.trim_start().starts_with("members"))
            .expect("workspace members line in Cargo.toml");
        for member in members_line
            .split(['[', ']', '"', ',', '='])
            .map(|s| s.trim())
            .filter(|s| !s.is_empty() && *s != "members")
        {
            if !readme.contains(&format!("{member}/")) {
                missing.push(format!("workspace member {member}"));
            }
        }

        assert!(
            missing.is_empty(),
            "README.md's Layout section doesn't name: {missing:?}"
        );
    }
}
